@extends('layouts.ai', ['title' => 'AI Command Dashboard'])

@section('content')
<div class="dashboard-wrap">
    <!-- Stat grid -->
    <div class="stat-grid" style="display:grid; grid-template-columns:repeat(auto-fit, minmax(220px, 1fr)); gap:20px; margin-bottom:32px;">
        <div class="glass-panel stat-card" style="display:flex; align-items:center; gap:16px;">
            <div class="stat-icon icon-blue" style="font-size:24px; padding:12px; border-radius:12px; background:rgba(15,111,255,0.1); color:#0f6fff;"><i class="fa-solid fa-bolt"></i></div>
            <div>
                <span class="stat-label" style="display:block; font-size:12px; color:var(--text-muted); font-weight:700;">TODAY'S AI CALLS</span>
                <strong class="stat-value" style="font-size:24px;">{{ $todayRequests }}</strong>
            </div>
        </div>
        <div class="glass-panel stat-card" style="display:flex; align-items:center; gap:16px;">
            <div class="stat-icon icon-purple" style="font-size:24px; padding:12px; border-radius:12px; background:rgba(139,92,246,0.1); color:#8b5cf6;"><i class="fa-solid fa-user-doctor"></i></div>
            <div>
                <span class="stat-label" style="display:block; font-size:12px; color:var(--text-muted); font-weight:700;">DOCTOR REQUESTS</span>
                <strong class="stat-value" style="font-size:24px;">{{ $doctorUsage }}</strong>
            </div>
        </div>
        <div class="glass-panel stat-card" style="display:flex; align-items:center; gap:16px;">
            <div class="stat-icon icon-green" style="font-size:24px; padding:12px; border-radius:12px; background:rgba(16,185,129,0.1); color:#10b981;"><i class="fa-solid fa-user-injured"></i></div>
            <div>
                <span class="stat-label" style="display:block; font-size:12px; color:var(--text-muted); font-weight:700;">PATIENT REQUESTS</span>
                <strong class="stat-value" style="font-size:24px;">{{ $patientUsage }}</strong>
            </div>
        </div>
        <div class="glass-panel stat-card" style="display:flex; align-items:center; gap:16px;">
            <div class="stat-icon icon-orange" style="font-size:24px; padding:12px; border-radius:12px; background:rgba(249,115,22,0.1); color:#f97316;"><i class="fa-solid fa-bullseye"></i></div>
            <div>
                <span class="stat-label" style="display:block; font-size:12px; color:var(--text-muted); font-weight:700;">ACCURACY RATING</span>
                <strong class="stat-value" style="font-size:24px;">{{ $accuracyPercentage }}%</strong>
            </div>
        </div>
    </div>

    <!-- CDSS Specific Alerts & Charts Split -->
    <div style="display:grid; grid-template-columns: 1.2fr 0.8fr; gap:24px; margin-bottom:32px; align-items:start;">
        <!-- Left: Chart -->
        <div class="glass-panel">
            <h2>AI Assistant Load & Trends</h2>
            <p style="color:var(--text-muted); font-size:13px; margin-bottom:20px;">Requests processed daily over the past week</p>
            <div style="height:320px; position:relative;">
                <canvas id="aiLoadChart"></canvas>
            </div>
        </div>

        <!-- Right: Real-time CDSS Active Warning Summary -->
        <div class="glass-panel">
            <h2>Active Clinical Warnings</h2>
            <p style="color:var(--text-muted); font-size:13px; margin-bottom:20px;">Unresolved alerts generated by triage or drug audits</p>
            <div style="display:flex; flex-direction:column; gap:14px;">
                <div class="stat-card" style="border:1px solid var(--glass-border); padding:14px; border-radius:8px; display:flex; justify-content:space-between; align-items:center;">
                    <div style="display:flex; align-items:center; gap:10px;">
                        <i class="fa-solid fa-triangle-exclamation" style="color:#ef4444;"></i>
                        <span>Critical Cases (EMR Vitals)</span>
                    </div>
                    <strong style="color:#ef4444;">{{ $criticalCases }}</strong>
                </div>
                <div class="stat-card" style="border:1px solid var(--glass-border); padding:14px; border-radius:8px; display:flex; justify-content:space-between; align-items:center;">
                    <div style="display:flex; align-items:center; gap:10px;">
                        <i class="fa-solid fa-capsules" style="color:#f59e0b;"></i>
                        <span>Drug Interactions</span>
                    </div>
                    <strong style="color:#f59e0b;">{{ $drugAlerts }}</strong>
                </div>
                <div class="stat-card" style="border:1px solid var(--glass-border); padding:14px; border-radius:8px; display:flex; justify-content:space-between; align-items:center;">
                    <div style="display:flex; align-items:center; gap:10px;">
                        <i class="fa-solid fa-vial-virus" style="color:#2563eb;"></i>
                        <span>Lab Alerts (Abnormal Vitals)</span>
                    </div>
                    <strong style="color:#2563eb;">{{ $labAlerts }}</strong>
                </div>
                <div class="stat-card" style="border:1px solid var(--glass-border); padding:14px; border-radius:8px; display:flex; justify-content:space-between; align-items:center;">
                    <div style="display:flex; align-items:center; gap:10px;">
                        <i class="fa-solid fa-gauge" style="color:#8b5cf6;"></i>
                        <span>Patient Risk Scores</span>
                    </div>
                    <strong style="color:#8b5cf6;">{{ $riskAlerts }}</strong>
                </div>
            </div>
            <div style="margin-top:20px; text-align:center;">
                <a href="{{ route('ai.alerts') }}" class="btn btn-soft" style="width:100%;">View Alerts Desk</a>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        const ctx = document.getElementById('aiLoadChart').getContext('2d');
        new Chart(ctx, {
            type: 'line',
            data: {
                labels: {!! json_encode($dailyRequests->pluck('date')) !!},
                datasets: [{
                    label: 'API Requests',
                    data: {!! json_encode($dailyRequests->pluck('count')) !!},
                    borderColor: '#0f6fff',
                    backgroundColor: 'rgba(15, 111, 255, 0.08)',
                    fill: true,
                    tension: 0.4,
                    borderWidth: 3
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: { display: false }
                },
                scales: {
                    y: { grid: { display: false } },
                    x: { grid: { display: false } }
                }
            }
        });

        // Simple entry GSAP fade-in micro-animation
        gsap.from(".stat-card", {
            duration: 0.6,
            opacity: 0,
            y: 20,
            stagger: 0.1,
            ease: "power2.out"
        });
    });
</script>
@endsection
